valor1 = input("Por favor, digite o primeiro valor: ")
valor2 = input("Por favor, digite o segundo valor: ")
soma = float(valor1)+float(valor2)
print("A soma entre os valores é {}".format(soma))
subtracao = float(valor1)-float(valor2)
print("A subtração entre os valores é {}".format(subtracao))
divisao = float(valor1)/float(valor2)
print("A divisão entre os valores é {}".format(divisao))
multiplicacao = float(valor1)*float(valor2)
print("A multiplicação entre os valores é {}".format(multiplicacao))