print("Olá esse é meu primeiro formulário criado via Python, por favor preencha os dados abaixo, não irei utilizá-los para nenhum fim comercial, apenas para teste mesmo. Obrigado")
name = input("Qual o seu nome? ")
sobrenome = input("Qual o seu segundo nome? ")
idade: int = input("Quantos anos você tem? ")
area_atuacao = input("Com o que você trabalha? ")
contato = input("Qual o seu e-mail? ")
print("Segue abaixo os dados para revisão:")
print("Nome = " + name)
print("Sobrenome = " + sobrenome)
print("Idade = {} " )